feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: VietNamese-SL

num_epoch: 2
work_dir: ./work_dir/VietNamese-SL/

batch_size: 1
test_batch_size: 1
num_worker: 0

device: -1
log_interval: 10
eval_interval: 1
save_interval: 1

evaluate_tool: sclite

loss_weights:
  SeqCTC: 1.0

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  start_epoch: 0

feeder_args:
  mode: 'train'
  datatype: 'video'
  drop_ratio: 1.0

model: slr_network.SLRModel
decode_mode: beam
model_args:
  c2d_type: resnet18
  conv_type: 2
  use_bn: 1
